spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:13370}/${DB_NAME:pokemon_manager}
    username: ${DB_USERNAME:xed}
    password: ${DB_PASSWORD:xed}
  liquibase:
    enabled: true
  application:
    name: pokemon-manager-api
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: ${SERVER_PORT:13372}
  shutdown: graceful

keycloak:
  auth-server-url: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:13371}/auth
  realm: ${KEYCLOAK_REALM:pokemon}
  resource: ${KEYCLOAK_CLIENT_ID:pokemon-client}
  bearer-only: true
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET:gUYaQZXdDOoT2bxM4WkQJ4hr8kPacMvo}
  ssl-required: external

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO