CREATE ROLE xed WITH
    LOGIN
    NOSUPERUSER
    CREATEDB
    NOCREATEROLE
    INHERIT
    NOREPLICATION
    CONNECTION LIMIT -1
    PASSWORD 'xed';

CREATE DATABASE pokemon_manager;

ALTER DATABASE pokemon_manager OWNER TO xed;
